// src/patch-script-template.ts — tweakcc adhoc-patch script for clodex patch.
//
// Ported from the relay-ai scripts/patch-custom-models wrapper. The script is
// executed inside tweakcc's sandbox with the Claude Code source as global `js`;
// clodex bakes the MODEL_CONFIG in between the clodex:config markers before
// handing the script to tweakcc (the sandbox cannot read files at runtime).
//
// Inspired by https://github.com/East-rayyy/claude-alias-patch (MIT); this is a
// from-scratch reimplementation applied through tweakcc's `adhoc-patch --script`
// mode with a different patch mechanism and an added per-model context window
// patch.
//
// Entries may omit `alias` — id-only entries still join the Agent-tool enum,
// the known-alias validator, and the context-window table, but skip the alias
// resolver and /model picker patches.

const CLODEX_CONFIG_START = '// clodex:config:start';
const CLODEX_CONFIG_END = '// clodex:config:end';

export interface PatchScriptModelEntry {
  alias?: string;
  context?: number;
}

/** Real model id (e.g. `clodex:openai-oauth:gpt-5.6-sol`) → alias/context. */
export type PatchScriptModelConfig = Record<string, PatchScriptModelEntry>;

const TEMPLATE = String.raw`/**
 * clodex patch — inject custom Claude Code model aliases (tweakcc adhoc-patch script).
 * Generated by clodex; do not edit. See clodex patch --help.
 */

// clodex:config:start
const MODEL_CONFIG = {};
// clodex:config:end

// ---- derive helpers --------------------------------------------------------
// alias -> model id (only for entries that define an alias)
const ALIAS_TO_ID = {};
// lowercased alias AND id -> context-window tokens (only for models that set it)
const CONTEXT_BY_KEY = {};
for (const [id, value] of Object.entries(MODEL_CONFIG)) {
  const spec = value && typeof value === "object" ? value : { alias: value };
  if (spec.alias !== undefined) {
    const a = String(spec.alias).trim().toLowerCase();
    if (!/^[a-z0-9][a-z0-9._-]*(\[1m\])?$/.test(a)) {
      throw new Error('clodex patch: alias "' + spec.alias + '" is not a safe lowercase alias');
    }
    ALIAS_TO_ID[a] = String(id);
  }

  if (spec.context !== undefined) {
    const n = Number(spec.context);
    if (!Number.isInteger(n) || n <= 0) {
      throw new Error('clodex patch: context for "' + id + '" must be a positive integer, got ' + spec.context);
    }
    // A [1m] suffix hard-codes 1M upstream (and sends the context-1m beta header
    // + raises the media cap). An explicit context on a [1m] model would win via
    // PATCH 7 while those side effects silently stayed on — so reject it.
    if (/\[1m\]/i.test(String(spec.alias ?? "")) || /\[1m\]/i.test(id)) {
      throw new Error(
        'clodex patch: "' + id + '" sets context but keeps the [1m] suffix — drop the suffix from both the id and the alias'
      );
    }
    if (spec.alias !== undefined) CONTEXT_BY_KEY[String(spec.alias).trim().toLowerCase()] = n;
    CONTEXT_BY_KEY[String(id).trim().toLowerCase()] = n;
  }
}
const ALIASES = Object.keys(ALIAS_TO_ID);
const MODELS = Object.keys(MODEL_CONFIG);
if (MODELS.length === 0) throw new Error("clodex patch: MODEL_CONFIG is empty");

const reEsc = (s) => s.replace(/[.*+?^$\{\}()|[\]\\]/g, "\\$&");
const q = (s) => JSON.stringify(s); // safe JS string literal

// ---- reporting -------------------------------------------------------------
const report = [];
function log(status, name, extra) {
  report.push({ status, name });
  const line = "  " + status.padEnd(4) + " " + name + (extra ? " — " + extra : "");
  // NOTE: tweakcc reads this script's STDOUT as the JSON result, so every
  // diagnostic MUST go to stderr — a stray stdout write corrupts the output.
  console.error(line);
}

/**
 * Apply exactly one regex replacement.
 *  - marker: if present in js, treat as already-patched -> SKIP.
 *  - expects exactly one match; 0 -> FAIL, >1 -> FAIL (ambiguous).
 *  - fn(match, ...groups) returns the replacement text.
 *  - required: on FAIL, throw (aborts the whole adhoc-patch).
 */
function applyOnce(name, regex, fn, { marker, required, noopIsSkip } = {}) {
  if (marker && js.includes(marker)) { log("SKIP", name, "already patched"); return; }
  const g = new RegExp(regex.source, regex.flags.includes("g") ? regex.flags : regex.flags + "g");
  const matches = js.match(g);
  const count = matches ? matches.length : 0;
  if (count === 0) {
    log("FAIL", name, "anchor not found");
    if (required) throw new Error("clodex patch: required patch failed: " + name);
    return;
  }
  if (count > 1) {
    log("FAIL", name, "anchor matched " + count + " times (expected 1)");
    if (required) throw new Error("clodex patch: ambiguous anchor: " + name);
    return;
  }
  const before = js;
  js = js.replace(regex, fn);
  if (js === before) {
    // For array-extend / append patches, "no change" means the aliases are
    // already present (anchor matched, but fn had nothing new to add) -> SKIP.
    if (noopIsSkip) { log("SKIP", name, "already patched"); return; }
    log("FAIL", name, "replacement made no change");
    if (required) throw new Error(name);
    return;
  }
  log("OK", name);
}

/** Insert missing ids just before the closing bracket of a JS array literal string. */
function extendAliasArray(arrLiteral) {
  const toAdd = MODELS.filter((a) => !new RegExp('"' + reEsc(a) + '"').test(arrLiteral));
  if (toAdd.length === 0) return arrLiteral; // idempotent
  return arrLiteral.replace(/\]\s*$/, "," + toAdd.map(q).join(",") + "]");
}

console.error("clodex patch: injecting models [" + MODELS.join(", ") + "]"
  + (ALIASES.length ? " aliases [" + ALIASES.join(", ") + "]" : ""));

// ---------------------------------------------------------------------------
// PATCH 1 — Agent/subagent tool 'model' zod enum.
// Anchor: .enum([ "sonnet",...,"fable" ]).optional().describe( — the array
// begins with the built-in aliases and is immediately followed by
// .optional().describe(. We append our ids inside the enum so the tool
// accepts them. (This same .describe( is patched by PATCH 4 below.)
// ---------------------------------------------------------------------------
applyOnce(
  "PATCH 1: Agent tool model enum",
  /\.enum\((\["sonnet","opus","haiku"(?:,"[^"]+")*\])\)\.optional\(\)\.describe\(/,
  (_m, arr) => ".enum(" + extendAliasArray(arr) + ").optional().describe(",
  { required: true, noopIsSkip: true }
);

// ---------------------------------------------------------------------------
// PATCH 3 — known-alias validator list (drives "is this a known alias?").
// Anchor: the master list literal, matched loosely as
// ["sonnet","opus","haiku","fable", ...anything... ,"opusplan"] so it
// tolerates new built-ins being added in the middle. Appending our ids
// makes them recognized as first-class aliases everywhere the gate runs.
// ---------------------------------------------------------------------------
applyOnce(
  "PATCH 3: known-alias validator list",
  /\["sonnet","opus","haiku","fable"(?:,"[^"]+")*,"opusplan"(?:,"[^"]+")*\]/,
  (m) => extendAliasArray(m),
  { required: true, noopIsSkip: true }
);

// ---------------------------------------------------------------------------
// PATCH 6 — alias -> model-id resolver switch.
// Anchor: case"best":{ ... } (the case"best":{ is unique). We inject
// case"<alias>":return"<model-id>"; right after it (before the switch's
// default:return null) so each alias resolves to its concrete model id.
// Only aliases not already present are inserted, so a rerun (or a config
// edit) tops up cleanly rather than duplicating cases.
// ---------------------------------------------------------------------------
{
  const missing = ALIASES.filter((a) => !new RegExp("case" + reEsc(q(a)) + ":return").test(js));
  const cases = missing.map((a) => "case" + q(a) + ":return " + q(ALIAS_TO_ID[a]) + ";").join("");
  if (ALIASES.length === 0) {
    log("SKIP", "PATCH 6: alias resolver switch", "no aliases configured");
  } else {
    applyOnce(
      "PATCH 6: alias resolver switch",
      /(case"best":\{[^{}]*\})/,
      (m) => m + cases,
      { required: true, noopIsSkip: true }
    );
  }
}

// ---------------------------------------------------------------------------
// PATCH 5 — interactive /model picker.
// The picker is assembled through a single choke-point function; we insert,
// right after its loop, a snippet that appends our custom
// {value,label,description} entries — with a runtime .some() dedupe guard so
// it is safe even if the function runs over the same array twice. Only
// aliases not already injected are added, so reruns top up cleanly.
// ---------------------------------------------------------------------------
{
  const missing = ALIASES.filter((a) => !new RegExp("value:" + reEsc(q(a))).test(js));
  const entries = missing
    .map(
      // ASCII only: tweakcc's script->JSON->repack path double-encodes any
      // non-ASCII byte.
      (a) => "{value:" + q(a) + ",label:" + q(a.charAt(0).toUpperCase() + a.slice(1)) + ",description:" + q("Custom model (" + ALIAS_TO_ID[a] + ")") + "}"
    )
    .join(",");
  const inject = missing.length
    ? "[" + entries + "].forEach(function(_o){if(!e.some(function(_i){return _i.value===_o.value}))e.push(_o)});"
    : "";
  if (ALIASES.length === 0) {
    log("SKIP", "PATCH 5: model picker options", "no aliases configured");
  } else {
    applyOnce(
      "PATCH 5: model picker options",
      /(\?\[[\w$]+,r\]:\[r\];for\(let [\w$]+ of [\w$]+\)[\w$]+\(e,[\w$]+,t\);)/,
      (m) => m + inject,
      { required: false, noopIsSkip: true }
    );
  }
}

// ---------------------------------------------------------------------------
// PATCH 4 — Agent tool 'model' parameter description text.
// Append the available model names before the closing backtick so the model
// knows the aliases exist and can request them. Best-effort (cosmetic).
// ---------------------------------------------------------------------------
{
  const listing = MODELS.join(", ");
  applyOnce(
    "PATCH 4: Agent tool model description",
    /(describe\(\`Optional model override for this agent[^\`]*?)(\`\))/,
    (_m, body, close) =>
      body.includes("custom aliases")
        ? body + close
        : body + " Additional custom aliases: " + listing + "." + close,
    { required: false, noopIsSkip: true }
  );
}

// ---------------------------------------------------------------------------
// PATCH 7 — per-model context window.
//
// Claude Code funnels EVERY context-window consumer (autocompact threshold,
// /context, the countdown, statusline, cost/usage records, subagent budgets)
// through one resolver function. We inject a baked table lookup at the TOP of
// that resolver, so it wins over the 200k clamp and the global
// CLAUDE_CODE_MAX_CONTEXT_TOKENS env override. Lookup is on the raw,
// lowercased model string — alias and id are both in the table, so it hits
// pre- or post-alias-resolution.
//
// Anchor: the resolver's exact body shape. Identifiers are wildcarded (they
// churn per build); the (e,t) arity + 3-statement shape matches once.
// ---------------------------------------------------------------------------
if (Object.keys(CONTEXT_BY_KEY).length) {
  const MARKER = "/*ccpatch:ctx*/";
  const SNIPPET =
    MARKER + 'var _ccw=(' + JSON.stringify(CONTEXT_BY_KEY) + ')[String(e||"").trim().toLowerCase()];if(_ccw!==void 0)return _ccw;';

  if (js.includes(MARKER)) {
    // Re-patching an already-patched binary: refresh the baked table in place
    // so a MODEL_CONFIG edit takes effect without a restore first.
    applyOnce(
      "PATCH 7: per-model context window (refresh)",
      /\/\*ccpatch:ctx\*\/var _ccw=\(\{[^{}]*\}\)\[[^\]]*\];if\(_ccw!==void 0\)return _ccw;/,
      () => SNIPPET,
      { required: true, noopIsSkip: true }
    );
  } else {
    applyOnce(
      "PATCH 7: per-model context window",
      /(function [\w$]+\(e,t\)\{)(let [\w$]+=[\w$]+\(\);if\([\w$]+!==void 0\)return [\w$]+;if\([\w$]+\(e,t\)\)return [\w$]+;return [\w$]+\(e,t\)\})/,
      (_m, head, body) => head + SNIPPET + body,
      { required: true }
    );
  }
}

// ---------------------------------------------------------------------------
const failed = report.filter((r) => r.status === "FAIL");
const ok = report.filter((r) => r.status === "OK").length;
const skip = report.filter((r) => r.status === "SKIP").length;
console.error("clodex patch: " + ok + " applied, " + skip + " skipped, " + failed.length + " failed");
if (failed.length) console.error("clodex patch: FAILED patches: " + failed.map((f) => f.name).join("; "));

return js;
`;

/** Render the tweakcc adhoc-patch script with the model config baked in. */
export function renderPatchScript(config: PatchScriptModelConfig): string {
  const start = TEMPLATE.indexOf(CLODEX_CONFIG_START);
  const end = TEMPLATE.indexOf(CLODEX_CONFIG_END);
  if (start < 0 || end < 0 || end < start) {
    throw new Error('clodex patch: config markers missing from patch script template');
  }
  const block = `${CLODEX_CONFIG_START}\nconst MODEL_CONFIG = ${JSON.stringify(config, null, 2)};\n${CLODEX_CONFIG_END}`;
  return TEMPLATE.slice(0, start) + block + TEMPLATE.slice(end + CLODEX_CONFIG_END.length);
}
